name: CI for Pizza planet
on:
  pull_request:
    branches:
    - "**"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install Pizza planet API
        uses: actions/checkout@v3
      
      - name: setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run tests and collect coverage
        run: pytest --cov=./  --cov-report=xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          files: ./coverage.xml
          flags: unittests
          name: codecov-pizza-planet
